### ISSUE TITLE
Make `:origins` a required option to avoid being insecure by default

### ISSUE THREAD

**Issue by thoughtless** [whatyouhide/corsica#33]
Currently Corsica is insecure by default. The default value of `:origins` is `"*"`.
https://github.com/whatyouhide/corsica/blob/2aeaeab219b58a81b0991bf9525d703caaf4eb8d/lib/corsica.ex#L70

This can lead an inexperienced developer to be believe that Corsica is configured correctly, but it is not. For example, a typo such as `origin: ["http://foo.com", "http://bar.com"]` will work for the happy path. But in reality the site will be insecure. If the user forgets to specify `:origins` the website will also be insecure.

Security best practice is for software to be [secure by default](https://www.owasp.org/index.php/Establish_secure_defaults). If Corsica is changed to default `:origins` to `[]` then users will quickly notice that they are not getting the expected CORS headers and that their configuration needs to be changed.
 
UPDATE: Title of PR updated to reflect the new behavior. See discussion below.

**Comment by whatyouhide** [comment]
@thoughtless heyo, thanks for the report. I definitely see your point. However, I also strive to make Corsica usable by people. Usually, what they do is drop Corsica in and if something doesn't work right away, it might become a user-unfriendly experience. So I am a bit on the fence on this. We can show all examples in the code and documentation as `plug Corsica, origins: "*"`, so that users can copy paste that in when they start with Corsica and it works.

**Comment by thoughtless** [comment]
The usability point is fair. But as it is it is quite easy to configure Corsica in an insecure way. Just adding `plug Corsica` to an app will open it up a number of different attacks.

The ideal is probably to require the `:origins` option to be set, and give an informative error if it is missing. I haven't done that with [my PR](https://github.com/whatyouhide/corsica/pull/34), instead I just changed the default to `[]`.

**Comment by thoughtless** [comment]
@bakkdoor FYI.

**Comment by whatyouhide** [comment]
Closed by #34.
